#!/usr/bin/env node
const fs = require('fs');
const file = require('file');
const path = require('path');
const chalk = require('chalk');
const mkdirp = require('mkdirp');
const { executeMe } = require('execute-me');

const { exportText } = require('./dist');
const { Parser } = require('./dist/parser');
const { Generator } = require('./dist/typescript/generate-interface');

const logger = {
  log(a = '') {
    console.log(a);
  },
  success(a = '') {
    console.log(`${chalk.green('success')} ${a}`);
  },
  error(a = '') {
    console.log(`${chalk.red('error')} ${a}`);
  },
  warning(a = '') {
    console.log(`${chalk.yellow('warning')} ${a}`);
  },
  pri(a = '') {
    console.log(`${chalk.blue(a)}`);
  }
};

function tsbuf(output = '.', mode = "global") {
  /**
   * protobuf-parser
   * Generate TypeScript interface with Protobuf.
   *
   * @version 0.1.0
   * @param {string} output - output path
   * @param {string} mode - "global": Global Definition, "module": Module Definition
   */
  const inputPath = arguments[arguments.length - 1][0];

  if (!inputPath) {
    logger.error('Input file is not specified.');
    process.exit(1);
  }

  const absoluteInputPath = path.resolve(inputPath);
  const ext = `${mode === 'global' ? '.d' : ''}.ts`;

  if (fs.lstatSync(absoluteInputPath).isFile()) {
    let outputPath = path.resolve(output);
    if (!outputPath.endsWith('.ts')) {
      outputPath = path.join(outputPath, `${fileName}${ext}`);
    }
    generateTs(absoluteInputPath, outputPath, mode);
    return;
  }

  file.walk(absoluteInputPath, (err, dirPath, dirs, files) => {
    for (const file of files) {
      if (!file.endsWith('.proto')) {
        continue;
      }
      const relativePath = path.relative(absoluteInputPath, file);
      const absolutePath = path.resolve(output, relativePath);
      const outputDir = path.dirname(absolutePath);
      const fileName = path.basename(absolutePath, '.proto');
      generateTs(file, path.resolve(outputDir, `${fileName}${ext}`), mode);
    }
  });
}

function generateTs(inputFileName, outputFileName, mode) {
  const proto = fs.readFileSync(inputFileName).toString();
  const ast = Parser.parse(proto);
  const generator = new Generator(ast);
  const interfaces = generator.getInterfaces();
  const text = exportText(interfaces, mode);

  mkdirp.sync(path.dirname(outputFileName));
  fs.writeFileSync(outputFileName, text);
  logger.success(`Generate ${outputFileName}`);
}

executeMe(tsbuf);
